name: Grab game list

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - '**.py'
      - '**.yml'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Run grab.py
      run: python grab.py
      
    - name: Update file
      continue-on-error: true
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull origin main
        git add 'json'
        git commit -F temp_commit.txt
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
